thermos:
  method-configs:
    thermosBackendService:
      requestVolumeThreshold: 2
      errorThresholdPercentage: 1
      requestCacheEnabled: false
      fallbackEnabled: false
    thermosTestService:
      requestVolumeThreshold: 3
      errorThresholdPercentage: 1
      requestCacheEnabled: false
      fallbackEnabled: true
