application.name: kinesis-client
#server.port: 6060

logging.path: ./build/logs
#logging.level.root: DEBUG

aws:
  region: "us-east-1"
  cloudWatch:
    protocol: "https"
    host: "localhost"
    port: 4582
    endpoint: "${aws.cloudWatch.protocol}://${aws.cloudWatch.host}:${aws.cloudWatch.port}"
  dynamoDB:
    protocol: "https"
    host: "localhost"
    port: 4569
    endpoint: "${aws.dynamoDB.protocol}://${aws.dynamoDB.host}:${aws.dynamoDB.port}"
    stream:
      fastLane:
        tableName: "fast-lane-dynamo-table"
      slowLane:
        tableName: "slow-lane-dynamo-table"
  kinesis:
    protocol: "https"
    host: "localhost"
    port: 4568
    endpoint: "${aws.kinesis.protocol}://${aws.kinesis.host}:${aws.kinesis.port}"
    worker:
      awaitTerminationInSeconds: 30
      threadPoolSize: 1
    stream:
      startupTimeoutInMillis: 30000
      maxRecordCount: 1
      idleTimeBetweenReadsInMillis: 250
      fastLane:
        name: "test-fast-lane"
        shardCount: 2
        threadPoolSize: 10
        maxConnections: "${aws.kinesis.stream.fastLane.threadPoolSize}"
        awaitTerminationInSeconds: 20
      slowLane:
        name: "test-slow-lane"
        shardCount: 2
        threadPoolSize: 2
        maxConnections: "${aws.kinesis.stream.slowLane.threadPoolSize}"
        awaitTerminationInSeconds: 20
