thermos:
  method-configs:
    thermosTestService:
      commandName: failingMethodValidation
      errorThresholdPercentage: 1
      requestVolumeThreshold: 3
      requestCacheEnabled: false
      fallbackEnabled: true
      requestLogEnabled: false
    thermosBackendService:
      commandName: getDataValidation
      errorThresholdPercentage: 1
      requestVolumeThreshold: 2
      requestCacheEnabled: false
      fallbackEnabled: false
      requestLogEnabled: false
