thermos:
  method-configs:
    thermosTestService:
      wrappedMethod:
        name: failingMethod
        argTypes: ""
      commandName: ${thermos.method-configs.thermosTestService.wrappedMethod.name}Validation
      groupName: ${thermos.method-configs.thermosTestService.commandName}Group
      errorThresholdPercentage: 1
      requestVolumeThreshold: 3
      requestCacheEnabled: false
      requestLogEnabled: false
      metrics.rollingStats.timeInMilliseconds: 5000
    thermosBackendService:
      wrappedMethod:
        name: getData
        argTypes: ""
      commandName: ${thermos.method-configs.thermosBackendService.wrappedMethod.name}Validation
      groupName: ${thermos.method-configs.thermosBackendService.commandName}Group
      errorThresholdPercentage: 1
      requestVolumeThreshold: 2
      requestCacheEnabled: false
      fallbackEnabled: false
      requestLogEnabled: false
      metrics.rollingStats.timeInMilliseconds: 5000
