thermos:
  method-configs:
    thermosTestService:
      commandName: failingMethodValidation
      errorThresholdPercentage: 1
      requestVolumeThreshold: 3
      requestCacheEnabled: false
      fallbackEnabled: false
      requestLogEnabled: false
      metrics.rollingStats.timeInMilliseconds: 5000
    thermosBackendService:
      commandName: getDataValidation
      errorThresholdPercentage: 1
      requestVolumeThreshold: 2
      requestCacheEnabled: false
      fallbackEnabled: false
      requestLogEnabled: false
      metrics.rollingStats.timeInMilliseconds: 5000
