thermos:
  method-configs:
    thermosBackendService:
      errorThresholdPercentage: 1
      requestVolumeThreshold: 2
      requestCacheEnabled: false
      fallbackEnabled: false
    thermosTestService:
      errorThresholdPercentage: 1
      requestVolumeThreshold: 4
      requestCacheEnabled: false
      fallbackEnabled: true
